spring.application.name=diaryBackend

#spring.datasource.url=jdbc:postgresql://localhost:5432/Diary
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.datasource.url=jdbc:postgresql://ep-cool-violet-a24rp1s5.eu-central-1.aws.neon.tech/diary?sslmode=require
spring.datasource.username=diary_owner
spring.datasource.password=iIpBl0nS7hbd

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
